Handle channel chat type
danyadev/vk-desktop pull request #113
Opened 2024-08-25 18:03 UTC by Binatik

- [x] - Отобразить если это канал старый за место участников => подписчиков канала.
- [ ] - Отработать с компонентом Button Icon - модифицируя компонент под "Отключить уведомления" 
- [ ] - Отобразить "отключить уведомление" если это старый канал.

2024-08-25 18:05 UTC, Binatik commented on src/ui/messenger/ConvoMessage/ConvoMessage.css
> +.ConvoMessage--channel {
У Нас нет div с датой сообщение, пока просто отступы сделал больше.

2024-09-11 20:19 UTC, danyadev requested changes

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoMessage/ConvoMessage.tsx
> +  convo: Convo.Convo
я думаю не стоит усложнять использование этого компонента и просто доставать конву внутри через message.peerId

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoMessage/ConvoMessage.tsx
> +          'ConvoMessage--channel': isChannel
похоже что этот класс здесь больше не нужен, стилей для него нет

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoView/ConvoView.tsx
> -    <div class="ConvoView">
зачем нужны такие правки в этом файле?

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoView/ConvoView.css
> +}
что делает этот стиль?

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +          lang: lang.locale
lang передавать не нужно, он сам проставляется в методе doFetch

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +          time: props.convo.notifications.disabledUntil,
я понимаю, что ты не разбираешься в том, как работает апи и что в него нужно совать, но делать рандомные вещи не стоит, лучше просто спросить

```
time: props.convo.notifications.enabled ? -1 : 0,
```

объяснение:
когда мы выключаем уведомления, мы делаем sound = 0 (без звука) и time = -1 (без ограничения по времени)

когда мы включаем уведомления, мы делаем sound = 1 (со звуком) и time = 0 (это поле в данном случае не нужно, мы просто отдаем 0 для его игнора)

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              mode="underline"
а что делает этот мод и зачем он нужен?

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              class={'ConvoComposer__btn-icon'}
class="ConvoComposer__actionButton"

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              }>
```tsx
before={
  props.convo.notifications.enabled
    ? <Icon24MuteOutline color="var(--vkui--color_icon_accent)" />
    : <Icon24VolumeOutline color="var(--vkui--color_icon_accent)" />
}
```

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              )}
```tsx
{props.convo.notifications.enabled
  ? lang.use('me_convo_disable_notifications')
  : lang.use('me_convo_enable_notifications')}
  ```

2024-09-11 20:19 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              onClick={toggleNotify}
toggleNotifications

2024-09-12 18:29 UTC, danyadev requested changes

2024-09-12 18:29 UTC, danyadev commented on src/lang/ru.ts
> +  me_convo_enabled_notifications: 'Включить уведомления',
enable, а не enabled

2024-09-12 18:29 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +                  : <Icon24VolumeOutline color="var(--vkui--color_icon_accent)"/>
ты пропустил пробелы перед закрывающими тегами

2024-09-12 18:29 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              class={'ConvoComposer__actionButton'}
фигурные скобки не нужны

2024-09-15 12:16 UTC, danyadev requested changes

2024-09-15 12:16 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +        console.log(error)
console.warn

2024-09-15 12:16 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +        loading.value = false
можем унести в finally блок

2024-09-15 12:16 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +              wide
больше не нужен

2024-09-15 12:48 UTC, danyadev requested changes

2024-09-15 12:48 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.tsx
> +                  : <Icon24VolumeOutline color="var(--vkui--color_icon_accent)" />
цвет можно опустить

2024-09-15 12:48 UTC, danyadev commented on src/ui/messenger/ConvoComposer/ConvoComposer.css
> +  min-height: 44px;
давай переместим min-height в panel (после padding), и поменяем его на 42px

2024-09-15 13:55 UTC, danyadev requested changes

2024-09-15 13:55 UTC, danyadev commented on src/ui/messenger/ConvoHeader/ConvoHeader.tsx
> +      </div>
можно сделать так:
```tsx
<div class="ConvoHeader__name">
  <span class="ConvoHeader__nameText">
    {Peer.name(peer)}
  </span>
  {!convo.notifications.enabled && <Icon16Muted color="var(--vkui--color_icon_tertiary)" />}
</div>
```

и в стилях прописать
```css
.ConvoHeader__name {
  gap: 3px;
}
```

как здесь, так и для ConvoListItem, где то же самое сделано

таким образом нам не нужен margin в ConvoHeader__nameIcons, который применяется даже когда иконок нет

2024-09-16 13:21 UTC, danyadev requested changes

2024-09-16 13:21 UTC, danyadev commented on src/styles.css
> +  /* ascent-override: 100%; */
а почему они закомменчены?

2024-09-16 15:32 UTC, danyadev requested changes

2024-09-16 15:32 UTC, danyadev commented on src/ui/messenger/ConvoHeader/ConvoHeader.tsx
> +        )}
1) давай назовем ConvoHeader__nameIcons; в будущем справа появятся кнопки, и может быть путаница в названиях
2) давай условие для рендера иконки оставим внутри враппера с иконками; сам враппер теперь ни на что не влияет, поэтому можно его оставить как есть, но если хочешь, можешь условие и для враппера оставить, в дальнейшем будем просто его расширять

2024-09-16 15:32 UTC, danyadev commented on src/ui/messenger/ConvoListItem/ConvoListItem.tsx
> +          )}
здесь так же

2024-09-16 15:32 UTC, danyadev commented on src/ui/messenger/MessagesStack/MessagesStack.tsx
> +        {message.kind === 'Normal' && dispayAvatar()}
не понял, зачем здесь оставлять одно условие, а там писать остальные
prettier в таком случае достаточно удобно форматирует:

```tsx
{message.kind === 'Normal' &&
  !message.isOut &&
  Peer.isChatPeerId(message.peerId) &&
  !Convo.isChannel(convo) && (
    <Avatar class="MessagesStack__avatar" peer={author} size={32} />
  )}
```

2024-09-16 20:07 UTC, merged